### ISSUE TITLE
my node never successfully auto-updates, or updates manually

### ISSUE THREAD

**Issue by momack2** [filecoin-station/filecoin-station#328] opened 2022-12-10 00:36 UTC
My node cant install new versions. I can manually install from the website and overwrite my whole node, but while my station node recognizes there is a new update, and will relaunch to try to upgrade to it, it never upgrades from 0.11.1 to 0.11.2 (and I had the same problem before moving from 0.9 to 0.11.1).

Here's my logs if useful:
[saturn.txt](https://github.com/filecoin-station/filecoin-station/files/10198883/saturn.txt)

**Comment by bajtos** [comment] 2022-12-12 15:44
Thank you for reporting the issue, @momack2! We are aware of the problem, see the discussion in https://github.com/filecoin-station/filecoin-station/issues/284 and #318. 

Our current conclusion is that the problem is caused by Electron not catching up with recent changes introduced by macOS Ventura - see https://github.com/electron-userland/electron-builder/issues/7121

FWIW, IPFS Desktop seems to be impacted too.

I am closing this issue as a duplicate of #284

**Closed by bajtos** 2022-12-12 15:44 UTC
